In [5]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
[1 2 3]
1 2 3


In [14]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
c = np.array([[1,2,3,4], [5,6,10,12], [6,8,9,1]])
print(c.shape)

(2, 3)
(3, 4)


In [12]:
# Numpy also provides many functions to create arrays:
z = np.zeros((4,6))
o = np.ones((2,5))
f = np.full((3,3),5)
e = np.eye(3)
r = np.random.random((4,4))
r

array([[0.3208767 , 0.48466035, 0.00942408, 0.03190139],
       [0.80902721, 0.98204255, 0.84845502, 0.6069487 ],
       [0.87456389, 0.65515393, 0.58839244, 0.4487474 ],
       [0.34051655, 0.08616559, 0.66758019, 0.5348802 ]])

In [16]:
# Array indexing
a = np.array([[1,2,3,4], [5,8,9,7],[6,10,12,17]])
print(a)
b = a[:2,1:3]
print(b)
b[0,0] = 77
print(b)

[[ 1  2  3  4]
 [ 5  8  9  7]
 [ 6 10 12 17]]
[[2 3]
 [8 9]]
[[77  3]
 [ 8  9]]


In [18]:
# Boolean array indexing
a = np.array([[1,2],[3,4],[5,6]])
bool_ind = (a>2)
print(bool_ind)
print(a.dtype)

[[False False]
 [ True  True]
 [ True  True]]
int64
